In [7]:
import pandas as pd
import numpy as np

In [8]:
T = []
TM = []
Tm = []
L = []
for i in range(9):
    T.append(pd.read_csv("../datos/Clima_full/T2019_0"+str(i+1)+".csv", encoding = 'Latin-1'))
    L.append(pd.read_csv("../datos/Clima_full/L2019_0"+str(i+1)+".csv", encoding = 'Latin-1'))
    TM.append(pd.read_csv("../datos/Clima_full/TM2019_0"+str(i+1)+".csv", encoding = 'Latin-1'))
    Tm.append(pd.read_csv("../datos/Clima_full/Tmin2019_0"+str(i+1)+".csv", encoding = 'Latin-1'))
    
T.append(pd.read_csv("../datos/Clima_full/T2019_10.csv", encoding = 'Latin-1'))
L.append(pd.read_csv("../datos/Clima_full/L2019_10.csv", encoding = 'Latin-1'))
TM.append(pd.read_csv("../datos/Clima_full/TM2019_10.csv", encoding = 'Latin-1'))
Tm.append(pd.read_csv("../datos/Clima_full/Tmin2019_10.csv", encoding = 'Latin-1'))
T.append(pd.read_csv("../datos/Clima_full/T2019_11.csv", encoding = 'Latin-1'))
L.append(pd.read_csv("../datos/Clima_full/L2019_11.csv", encoding = 'Latin-1'))
TM.append(pd.read_csv("../datos/Clima_full/TM2019_11.csv", encoding = 'Latin-1'))
Tm.append(pd.read_csv("../datos/Clima_full/Tmin2019_11.csv", encoding = 'Latin-1'))

In [9]:
for i in range(11):
    T[i] = T[i].rename(columns={"Tmed":"Tmed_"+str(i+1)})
    TM[i] = TM[i].rename(columns={"Tmax":"Tmax_"+str(i+1)})
    Tm[i] = Tm[i].rename(columns={"Tmin":"Tmin_"+str(i+1)})
    print(Tm[i].columns)

Index(['Lon', 'Lat', 'Clave', 'Edo', 'Est', 'Tmin_1'], dtype='object')
Index(['Lon', 'Lat', 'Clave', 'Edo', 'Est', 'Tmin_2'], dtype='object')
Index(['Lon', 'Lat', 'Clave', 'Edo', 'Est', 'Tmin_3'], dtype='object')
Index(['Lon', 'Lat', 'Clave', 'Edo', 'Est', 'Tmin_4'], dtype='object')
Index(['Lon', 'Lat', 'Clave', 'Edo', 'Est', 'Tmin_5'], dtype='object')
Index(['Lon', 'Lat', 'Clave', 'Edo', 'Est', 'Tmin_6'], dtype='object')
Index(['Lon', 'Lat', 'Clave', 'Edo', 'Est', 'Tmin_7'], dtype='object')
Index(['Lon', 'Lat', 'Clave', 'Edo', 'Est', 'Tmin_8'], dtype='object')
Index(['Lon', 'Lat', 'Clave', 'Edo', 'Est', 'Tmin_9'], dtype='object')
Index(['Lon', 'Lat', 'Clave', 'Edo', 'Est', 'Tmin_10'], dtype='object')
Index(['Lon', 'Lat', 'Clave', 'Edo', 'Est', 'Tmin_11'], dtype='object')

In [10]:
Tmed = pd.merge(T[0], pd.merge(T[1], pd.merge(T[2], pd.merge(T[3], pd.merge(T[4], pd.merge(T[5], 
              pd.merge(T[6], pd.merge(T[7], pd.merge(T[8], pd.merge(T[9], T[10]))))))))))
Tmax = pd.merge(TM[0], pd.merge(TM[1], pd.merge(TM[2], pd.merge(TM[3], pd.merge(TM[4], pd.merge(TM[5], 
              pd.merge(TM[6], pd.merge(TM[7], pd.merge(TM[8], pd.merge(TM[9], TM[10]))))))))))
Tmin = pd.merge(Tm[0], pd.merge(Tm[1], pd.merge(Tm[2], pd.merge(Tm[3], pd.merge(Tm[4], pd.merge(Tm[5], 
              pd.merge(Tm[6], pd.merge(Tm[7], pd.merge(Tm[8], pd.merge(Tm[9], Tm[10]))))))))))

In [11]:
Temperatura = pd.merge(Tmed, pd.merge(Tmin, Tmax))
Temperatura

,Lon,Lat,Clave,Edo,Est,Tmed_1,Tmed_2,Tmed_3,Tmed_4,Tmed_5,...,Tmax_2,Tmax_3,Tmax_4,Tmax_5,Tmax_6,Tmax_7,Tmax_8,Tmax_9,Tmax_10,Tmax_11
0,-101.47,21.07,COMGJ,GTO,Comanjilla Gto.,15.846774,18.134615,20.056452,20.482143,22.854839,...,28.846154,30.483871,31.107143,32.806452,30.807692,27.965517,29.130435,27.6,27.7,27.7
1,-101.22,21.48,SFEGJ,GTO,San Felipe Gto.,11.250000,14.500000,16.451613,17.316667,20.258065,...,24.178571,26.387097,27.100000,29.580645,26.266667,24.645161,25.766667,23.2,22.8,21.5
2,-98.76,18.88,OCTMR,MOR,Ocuituco Mor.,17.416129,19.866071,20.991935,21.580000,22.250000,...,29.053571,29.806452,30.720000,30.209677,24.981481,23.206897,25.425926,24.5,23.7,24.3
3,-107.76,25.12,RAVSI,SIN,Estaci√≥n Rancho Viejo Sin.,20.290323,20.461538,21.796296,23.354167,24.775000,...,30.269231,33.148148,34.250000,35.600000,37.428571,38.321429,36.516000,35.1,35.5,33.0
4,-95.03,18.52,SONVC,VER,Sontecomapan Ver.,20.009259,22.107143,22.066667,23.966667,28.951613,...,27.660714,27.750000,30.966667,35.774194,33.055556,32.354839,33.566667,32.5,30.7,27.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,-103.50,22.33,STEZC,ZAC,Santa Teresa Zac.,13.669355,15.576923,18.080645,17.926667,20.879032,...,24.750000,27.500000,27.870000,30.725806,31.016667,26.887097,27.467742,26.3,26.0,23.7
470,-99.15,22.99,AHLTP,TAMPS,Ahualulco Tamps.,19.508621,22.465385,23.594444,26.890000,29.941935,...,29.380769,29.525926,34.813333,35.558065,36.060714,35.641935,37.932258,34.9,31.9,27.0
471,-107.26,28.77,BACCH,CHIH,Bach√≠niva Chih.,7.629032,8.839286,12.854839,14.583333,17.258065,...,16.571429,21.580645,23.666667,26.483871,31.074074,29.000000,27.935484,24.9,22.0,18.8
472,-103.73,22.40,BCSJL,JAL,Bocas Jal.,14.838710,17.692308,20.250000,20.308333,23.798387,...,30.557692,33.187500,33.883333,36.403226,36.000000,32.533333,32.700000,32.1,31.3,27.8
473,-89.50,21.08,CONYC,YUC,Conkal Yuc.,20.870968,24.803571,25.096774,27.033333,29.604839,...,32.964286,33.483871,35.600000,37.870968,36.400000,34.096774,35.525806,35.0,33.4,29.3

In [12]:
Temperatura.to_csv("../datos/TEMPERATURAS_2019_MENSUAL.csv")