In [127]:
import pandas as pd
import numpy as np

#Cargamos los archivos .csv a un DataFrame
tempMax = pd.read_csv("temperatura_maxima.csv", encoding = 'Latin-1')
tempMid = pd.read_csv("temperatura_media.csv", encoding = 'Latin-1')
tempMin = pd.read_csv("temperatura_minima.csv", encoding = 'Latin-1')
lluvia18 = pd.read_csv("lluvia2018.csv", encoding = 'Latin-1')
lluvia19 = pd.read_csv("lluvia2019.csv", encoding = 'Latin-1')
lluvia20 = pd.read_csv("lluvia2020.csv", encoding = 'Latin-1')

In [128]:
#Hacemos merge de las tres tablas. Usamos how = left para evitar que quite filas 
#donde falten entradas y mejor los llene con un NaN
temperatura = pd.merge(tempMax, pd.merge(tempMin, tempMid, how = 'left'), how = 'left')

#Creamos un indice multiple, de estado y localidad. Usamos sort.index() para ordenar 
#los estados por orden alfabetico
temperatura = temperatura.set_index(['Edo', 'Est', 'Clave']).sort_index(level = 0)

#Cambiamos los nombres de las columnas del indice multiple
temperatura = temperatura.rename_axis(['Estado', 'Localidad', 'Clave'])

#Previsualizamos la tabla
display(temperatura)

                                               Lon    Lat       Tmax  \
Estado Localidad                  Clave
AGS    AGUASCALIENTES             76571    -102.29  21.85  22.941935
       Aguascalientes Ags.        AGSAG    -102.31  21.90  23.467742
       Calvillo Ags. SMN*         CALVILLO -102.71  21.85  26.522581
       Cincuenta Aniversario Ags. ANVAG    -102.47  22.19  22.722581
       Cosío Ags.                 CSOAG    -102.30  22.36  18.080645
...                                            ...    ...        ...
ZAC    Sombrerete Zac.            SOMZC    -103.64  23.64  22.129032
       Villa Hidalgo Zac.         VHGZC    -101.72  22.35  19.806452
       ZACATECAS                  76525    -102.57  22.78  15.932258
       Zacatecas Zac.             ZACZC    -102.58  22.76  19.870968
       Zacatecas Zac. SMN*        ZA2ZC    -102.51  22.75  20.361290

                                                Tmin       Tmed
Estado Localidad                  Clave
AGS    AGUASCALIENTES             76571          NaN        NaN
       Aguascalientes Ags.        AGSAG     6.403226  14.935484
       Calvillo Ags. SMN*         CALVILLO  3.874194  15.198387
       Cincuenta Aniversario Ags. ANVAG     5.422581  14.072581
       Cosío Ags.                 CSOAG     0.790323   9.435484
...                                              ...        ...
ZAC    Sombrerete Zac.            SOMZC     5.012903  13.570968
       Villa Hidalgo Zac.         VHGZC     1.870968  10.838710
       ZACATECAS                  76525     7.441935  11.687097
       Zacatecas Zac.             ZACZC     7.693548  13.782258
       Zacatecas Zac. SMN*        ZA2ZC     5.445161  12.903226

[722 rows x 5 columns]

In [129]:
temperatura.to_csv("TEMPERATURAS2019.csv")

In [130]:
#Renombramos nombres de columnas para que coincidan y hacer el merge
#Pudimos haber indicado que son lo mismo sin cambiar el nombrem pero
#lo hacemos por si las tenemos que manipular de nuevo
lluvia19 = lluvia19.rename(columns={"EDO":"ESTADO"})
lluvia19 = lluvia19.rename(columns={"ESTACION":"NOMBRE"})
lluvia19 = lluvia19.rename(columns={"JUL":"2019"})

lluvia18 = lluvia18.rename(columns={"CLAVE_SIH":"CLAVE"})
lluvia18 = lluvia18.rename(columns={"ENE":"2018"})

lluvia20 = lluvia20.rename(columns={"CLAVE_SIH":"CLAVE"})
lluvia20 = lluvia20.rename(columns={"ENE":"2020"})

In [131]:
#Repetimos lo mismo que con la tabla de temperaturas
lluvias = pd.merge(lluvia20, pd.merge(lluvia18, lluvia19, how = 'left'), how = 'left')
lluvias = lluvias.set_index(['ESTADO', 'NOMBRE', 'CLAVE']).sort_index()

In [132]:
lluvias

                                               LON        LAT  2020  2018  \
ESTADO NOMBRE          CLAVE
AGS    Aguascalientes  ELBECERRO       -102.183889  21.978000  17.6  17.6
                       ELCEDAZO        -102.259328  21.864800  14.2  14.2
                       GranjaElsa      -102.263886  21.785300   9.4   9.4
                       LALAGUNITA      -102.128306  21.780389   8.2   8.2
                       LASALADA        -102.362917  21.816717   0.0   0.0
...                                            ...        ...   ...   ...
ZAC    Villa de Cos    CHAPARROSA      -102.271944  23.039167  43.0  43.0
                       SIERRAVIEJA     -102.178472  23.457750  38.6  38.6
       Zacatecas       UAAGRONOMIA     -102.686222  22.724556  36.4  36.4
                       ZACATECAS_ESIME -102.566389  22.778333  21.4  21.4
       Zacatecas, Zac. ZACZC           -102.576667  22.761389  43.3  43.3

                                        2019
ESTADO NOMBRE          CLAVE
AGS    Aguascalientes  ELBECERRO         NaN
                       ELCEDAZO          NaN
                       GranjaElsa        NaN
                       LALAGUNITA        NaN
                       LASALADA          NaN
...                                      ...
ZAC    Villa de Cos    CHAPARROSA        NaN
                       SIERRAVIEJA       NaN
       Zacatecas       UAAGRONOMIA       NaN
                       ZACATECAS_ESIME   NaN
       Zacatecas, Zac. ZACZC            59.0

[1884 rows x 5 columns]

In [133]:
#Guardamos la tabla generada
lluvias.to_csv("LLUVIAS-2018-2020.csv")